import { Product, Category } from '@/types';

export const categories: Category[] = [
  {
    id: 'polish',
    name: 'Nail Polish',
    description: 'Wide range of nail polish colors and finishes',
  },
  {
    id: 'tools',
    name: 'Nail Tools',
    description: 'Professional nail care tools and equipment',
  },
  {
    id: 'art',
    name: 'Nail Art Supplies',
    description: 'Everything for creative nail art designs',
  },
  {
    id: 'care',
    name: 'Nail Care',
    description: 'Products for healthy and strong nails',
  },
];

export const products: Product[] = [
  {
    id: '1',
    name: 'Classic Red Nail Polish',
    description: 'Long-lasting red nail polish with a glossy finish. Perfect for any occasion.',
    price: 12.99,
    category: 'polish',
    image: '/images/red-polish.jpg',
    inStock: true,
    colors: ['Red', 'Deep Red', 'Cherry Red'],
  },
  {
    id: '2',
    name: 'Professional Nail File Set',
    description: 'Set of 5 professional-grade nail files with different grits for perfect shaping.',
    price: 15.99,
    category: 'tools',
    image: '/images/nail-file-set.jpg',
    inStock: true,
  },
  {
    id: '3',
    name: 'Glitter Nail Art Kit',
    description: 'Complete kit with 12 colors of fine glitter for stunning nail art designs.',
    price: 24.99,
    category: 'art',
    image: '/images/glitter-kit.jpg',
    inStock: true,
  },
  {
    id: '4',
    name: 'Cuticle Oil Treatment',
    description: 'Nourishing cuticle oil with vitamin E for healthy, hydrated cuticles.',
    price: 9.99,
    category: 'care',
    image: '/images/cuticle-oil.jpg',
    inStock: true,
  },
  {
    id: '5',
    name: 'Pastel Pink Polish',
    description: 'Soft pastel pink nail polish, ideal for a natural and elegant look.',
    price: 11.99,
    category: 'polish',
    image: '/images/pink-polish.jpg',
    inStock: true,
    colors: ['Light Pink', 'Rose Pink', 'Baby Pink'],
  },
  {
    id: '6',
    name: 'Electric Nail Drill',
    description: 'Professional electric nail drill with adjustable speed for perfect manicures.',
    price: 79.99,
    category: 'tools',
    image: '/images/nail-drill.jpg',
    inStock: true,
  },
  {
    id: '7',
    name: 'Nail Sticker Set',
    description: 'Assorted nail stickers with various designs - flowers, geometric patterns, and more.',
    price: 8.99,
    category: 'art',
    image: '/images/nail-stickers.jpg',
    inStock: true,
  },
  {
    id: '8',
    name: 'Strengthening Base Coat',
    description: 'Fortifying base coat that strengthens nails and prevents chipping.',
    price: 14.99,
    category: 'care',
    image: '/images/base-coat.jpg',
    inStock: true,
  },
  {
    id: '9',
    name: 'Midnight Blue Polish',
    description: 'Deep midnight blue nail polish with shimmer for a sophisticated look.',
    price: 13.99,
    category: 'polish',
    image: '/images/blue-polish.jpg',
    inStock: true,
    colors: ['Midnight Blue', 'Navy Blue'],
  },
  {
    id: '10',
    name: 'UV LED Nail Lamp',
    description: 'Professional UV LED lamp for curing gel polish quickly and evenly.',
    price: 49.99,
    category: 'tools',
    image: '/images/uv-lamp.jpg',
    inStock: false,
  },
  {
    id: '11',
    name: 'Rhinestone Collection',
    description: 'Premium rhinestone collection with various sizes and colors for nail decoration.',
    price: 18.99,
    category: 'art',
    image: '/images/rhinestones.jpg',
    inStock: true,
  },
  {
    id: '12',
    name: 'Nail Repair Kit',
    description: 'Complete repair kit for broken or split nails with silk wraps and glue.',
    price: 16.99,
    category: 'care',
    image: '/images/repair-kit.jpg',
    inStock: true,
  },
];
